### ISSUE TITLE
Reminder: Back out hardcoded mdbook v0.2.1 version

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/embedonomicon#32]
See #31 and rust-embedded/book#59

**Comment by austinglaser** [comment]
This is ready to address (I'm happy to do so some time this week). It's basically as simple as https://github.com/rust-embedded/docs/pull/21.

I'll also do a brief audit of the documentation produced by the newer `mdbook`.  At the minimum, there are likely to be several places where attributes are accidentally swallowed (a la https://github.com/rust-embedded/book/pull/212)

**Comment by austinglaser** [comment]
Looks like the issue with rendering attributes was fixed in mdbook v0.3.5
