### ISSUE TITLE
host on https://embedonomicon.rust-embedded.org

### ISSUE THREAD

**Issue by japaric** [rust-embedded/embedonomicon#4]
@jamesmunns what would be the way to go here? Set travis CI to re-generate the gh-pages on each commit and use the CNAME file to set embedonomicon.rust-embedded.org as the domain name?

It seems GH pages now support https with custom domain names: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by jamesmunns** [comment]
Hey @japaric, I'd suggest we get all the books (and anything else) moved over to the rust-embedded space, and once there is Github pages/Travis CI set up, we can talk to Nick Stevens about updating the DNS/CNAME records.

**Comment by japaric** [comment]
Triage: blocked on rust-embedded/wg#156

**Comment by japaric** [comment]
Done in rust-embedded/wg#156.
