### ISSUE TITLE
Can you replicate the examples on Windows?

### ISSUE THREAD

**Issue by japaric** [rust-embedded/embedonomicon#8]
Let us know if you had to significantly deviate from the instructions! (Other than using different built-in commands if you were using cmd instead of bash).

**Comment by nateglims** [comment]
I have an issue with the windows version of Qemu 3.0.0 but in an Ubuntu VM I could run the exact same binary fine with Qemu 2.5.0. I haven't tried that version on windows yet.

After forwarding the gdb port on the VM back to windows, I could get arm-none-eabi-gdb to work but had issues with the windows version of LLDB.

**Comment by nateglims** [comment]
This [package includes QEMU and qemu-system-arm](https://qemu.weilnetz.de/w64/) I found it because it was linked from [the qemu website](https://www.qemu.org/download/#windows)

**Comment by LokiFaun** [comment]
I installed from the same link  @nateglims mentioned.
